# Generated by Django 4.1.7 on 2023-02-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=10)),
                ("altitude", models.IntegerField()),
                ("vertical_angle", models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
