# Generated by Django 4.1.7 on 2023-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name="location",
            name="vertical_angle",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
