# Generated by Django 4.1.7 on 2023-02-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beam", "0002_alter_location_latitude_alter_location_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="senarios"),
        ),
        migrations.AddField(
            model_name="location",
            name="senario",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
