# Generated by Django 4.1.7 on 2023-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beam", "0003_location_image_location_senario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="image",
            new_name="image_beam",
        ),
        migrations.AddField(
            model_name="location",
            name="image_couverture",
            field=models.ImageField(default="default.jpg", upload_to="senarios"),
        ),
    ]
